### ISSUE TITLE
RFC 202304162103 - Standardising and Unifying Connector Kits (SUCK)

### ISSUE THREAD

**Issue by frroossst** [USSTR-Avionics/Mumbai#2]
How do our boards communicate with each other and what does the connector looks like

**Comment by frroossst** [comment]
So, in essence the SUCK or the Standard Unified Connector Kit would have
5V
3V3
GND
4x CAN (don't know how many wires can takes)
GPIOS (number to be specified)

**Comment by ATGr8** [comment]
Dont need 4 CAN wires, just two wires: CANH and CANL, so just 2

**Comment by AstroJosh2002** [comment]
have a common connector for all boards and only connect what you need on each board

**Comment by frroossst** [comment]
We might need a separate bus to not bog down the main CANbus line for things like, images from a camera, or something that takes up a lot of bandwidth

**Comment by dhaussecker** [comment]
Why can't you use CAN for everything? Connect sensors to a MCU and that MCU goes to CAN BUS

**Comment by dhaussecker** [comment]
What type of sensors would connect to these GPIOs? Are these flight critical sensors?

**Comment by ATGr8** [comment]
We don't know yet, but we need the flexibility to add non complex boards that can just plug into the GPIOs, adding a MCU for such boards is overkill and add more points of failure.

**Comment by dhaussecker** [comment]
Each board will have standard GPIOs so if a sensor needs to be added to the rocket in a certain location in the future, it can be easily done. It is a transportation system between all boards (priority based) using CAN to easily replace and add more sensors

**Comment by frroossst** [comment]
finally!!!!

**Comment by frroossst** [comment]
PC104 ftw

**Comment by dhaussecker** [comment]
All Boards IN THE STACK can use PC104 Connectors, as long as they will meet launch Canada Requirements

**Comment by dhaussecker** [comment]
Boards in other sections of the rocket will need something else, determined later

**Comment by frroossst** [comment]
you can't just comment things here that we tell you on discord!

**Comment by dhaussecker** [comment]
ALL STANDARDS ARE SUBJECT TO DESIGN CHANGES IF DEEMED NECESSARY IN THE FUTURE

**Comment by AstroJosh2002** [comment]
I approve the current design

**Comment by frroossst** [comment]
approve deez nuts

**Comment by frroossst** [comment]
CENSORSHIP!

**Comment by AstroJosh2002** [comment]
I can't believe we spent more than 30 mins convincing Dylan why GPIO is a good idea

**Comment by frroossst** [comment]
# Pinout 
(left to right, topview)

|  | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
|---|---|---|---|---|---|---|---|---|---|---|
| **A** | GND | 3V3 |GND | 3V3 | GND | 5V | GND | 5V | GND | Bus voltage | 
| **B** | GND | CAN high | CAN low | GND | GPIO | GPIO | GPIO | GPIO | GPIO  | GPIO 

10x2 connector

**Comment by AstroJosh2002** [comment]
https://www.digikey.com/en/products/detail/samtec-inc/ESQ-105-23-S-D/7090235

**Comment by ATGr8** [comment]
https://www.digikey.ca/en/products/detail/sullins-connector-solutions/SFH11-PBPC-D10-ST-BK/1990090
I like this one cause it has a indication of first row so we cant flip it

**Comment by AstroJosh2002** [comment]
https://www.mouser.ca/c/connectors/backplane-connectors/pc-104-connectors/?q=ESQ&number%20of%20positions=20%20Position

**Comment by ATGr8** [comment]
https://www.digikey.ca/en/products/filter/rectangular-connectors/headers-receptacles-female-sockets/315?s=N4IgjCBcoBw1oDGUBmBDANgZwKYBoQB7KAbXAGYB2SgTgDYQBdAgBwBcoQBlNgJwEsAdgHMQAXwIAmMJUkIQySOmz4ipEHOYh2nAJKC2OYTl7ixYoA 
Digikey filter for us

**Comment by AstroJosh2002** [comment]
Header dimentions https://suddendocs.samtec.com/prints/esq-1xx-xx-x-x-xxx-xx-x-xx-mkt.pdf

**Comment by AstroJosh2002** [comment]
https://www.mouser.ca/ProductDetail/Samtec/ESQ-110-38-G-D?qs=0lQeLiL1qya%252BPHAV3ltgtA%3D%3D

**Comment by AstroJosh2002** [comment]
Probably the best one https://www.mouser.ca/ProductDetail/Samtec/ESQ-110-13-G-D?qs=0lQeLiL1qyaTGIi6Og3PNg%3D%3D
