### ISSUE TITLE
RFC 202304242108: We do *not* need a memory board 

### ISSUE THREAD

**Issue by frroossst** [USSTR-Avionics/Mumbai#5]
- adding a memory board or data logger can create unnecessary redundancy and add complexity to the system.
-  it would need to be programmed to collect data from the other boards, which can create a risk of data loss or communication errors.
- the added weight and size of the memory board or data logger can affect the overall performance of the rocket and potentially impact the flight trajectory.
- centralised board introduces a single point of failure
- If each board logs its own data, it can be done at a higher frequency or a different tick rate than a centralized memory logger. This can provide more accurate and detailed information about the performance of each component, which can be useful for troubleshooting and analysis.
- With each board logging its own data, it can be easier to identify which specific component or subsystem caused any issues during flight. This can help to pinpoint problems and make improvements for future launches.
- With each board logging its own data, it can be easier to identify and isolate any faults or issues that occur during flight. This can help to improve fault tolerance and make the rocket more resilient to future failures.
- With each board logging its own data, the data can be easily transferred to a computer for analysis without the need for a centralized memory logger. This can simplify the data transfer process and reduce the risk of data loss or corruption during transfer.
- Each board can be programmed to log specific data points that are relevant to its function, rather than having to log all data on a centralized logger. This can help to optimize the use of storage space and improve the accuracy of the data collected.
- With each board logging its own data, it can be possible to perform real-time data analysis during flight. This can allow for immediate adjustments to be made if any issues are detected, improving the overall performance and safety of the rocket.
- If each board logs its own data, it can be easier to swap out individual components or subsystems without affecting the data collection process. This can help to improve the modularity of the rocket and make it easier to upgrade or repair.

> Disclaimer: This post is not associated with the Rust Foundation :tm: and powered by chatGPT

**Comment by ATGr8** [comment]
I agree, we do not need a data logger board, it adds complexity that is not necessary and we can just log data from the board the data is coming from in the first place

**Comment by AstroJosh2002** [comment]
I'm also in agreement that having more points of failure in the system will cause more problems not only in flight but also during testing. If you have the option to put storage space on the flight computer, why have a seperate board for logging the data to when you can put a larger amount of storage space on your flight computer. Also having more information flowing on the CAN Bus lines has the risk of slowing it down, this can be dangerous when the flight computer needs to make timely decisions and if that's delayed it can put people's safety at risk

**Comment by frroossst** [comment]
Here are a few ways we can store data if using a central data logger, the important assumption being data comes in at different tick rates.

1. Have a different chip for every different data type
    - Inefficient to scale
    - Cannot easily change the schema
        
2. Attach a tagging field
    - Wasting space (would need at least two more bytes, one for the data type being stored and one for how many bytes follow that
    
3. Hashing
    - Impossible to create a hash function that would have zero collisions 
    
4. Serialising a data chunk
    - Would waste space if a data element is ticked in extremely fast

5. Round Robin Circular Buffer data chunk serialisation
    - Probably the best solution
    - Very space efficient (stores the same amount as the actual data being stored)
    - Difficult to implement, still would waste some space overall

---
This however still does not solve my further hesitation, if any given board does not have any onboard memory chips to store data then while debugging I'll always need to have two boards connected over CAN when debugging, if any given board does indeed have some memory chips on board for quick storage and access then why not increase that storage space and eliminate the memory board altogether?

**Comment by frroossst** [comment]
/remind me about RFC vote in 4 days

**Comment by dhaussecker** [comment]
As discussed previously, you are free to implement data logging functionality on the flight computer. we are implementing a data logger board right now for the case that you fail in successfully implementing it on the flight computer which I have deemed it has a high risk at this point with all the other priorities of this board, and time for programming. Prove me wrong 😉 I think a data logger board  would be the perfect “black box” of the system just like airplanes have used for the purposes of redundancy.

**Comment by frroossst** [comment]
Again, the central problem with a data logger is an implementation scheme that is memory efficient with all that data coming in at different rates in a non-specific order.

If your data logger fails then you loose 100% of the data, it adds one more board, one more microcontroller to program, one more point of failure. If data logging is handled by each board then we can in theory loose multiple boards while still being able to salvage back some data. A centralised data-logger adds one more layer of complexity. 

As @ATGr8 pointed out before, it needs to be a closed loop system, if your data logger shits the bed, then the flight computer cannot get back data. 

Also, why would we fail to implement a datalogger on the flight computer? We literally did it on the MiniRocket. 

Sidenote: there is no point of an RFC system, if decisions are made unilaterally,

**Comment by dhaussecker** [comment]
I believe you are confusing points of failure and extra complexities with redundancies. This is a redundancy which launch Canada wants for all essential systems. I agree with having a chip on every board for the purpose of redundancy

**Comment by frroossst** [comment]
Show me where Launch Canada says, we need to have redundancy for data logging

**Comment by Ukrainianvengeance** [comment]
How would the control system get all of the flight data? and would we need separate ground stations for each PCB?

**Comment by frroossst** [comment]
What do you mean by control system? The flight computer? or the Ground Station?

If you are talking about the flight computer then CANbus? if the ground station then just CANbus and then the radio board handles it?

Can you elaborate a little more on your question?

**Comment by Ukrainianvengeance** [comment]
I think I misunderstood yesterday, the data logger would just store the data not process and use the data for flight, right?

**Comment by frroossst** [comment]
Yes, it would just be storing the data. Do you have any concerns or questions about it?

**Comment by Ukrainianvengeance** [comment]
I no longer have concerns about it and agree with your conclusion as to not needing a central data logger

**Comment by bristinemuluh** [comment]
One of our most important goals is modularity and I think having a centralized data logger would make it a little more difficult and messy to add new boards to our system. I think  having each board do its own data collection will help a lot in making our boards modular. It'll also be a lot simpler to test and debug. Also if we decided to swap a board or change stuff on it, we won't need to also make changes to a data logger ( which might affect other boards).

**Comment by frroossst** [comment]
Eligible voters: @ATGr8 @AstroJosh2002 @bristine02 @dhaussecker @frroossst @Ukrainianvengeance 

:+1: if you are **in support** of the RFC, i.e. there **shouldn't** be a centralised memory logger on board
:-1: if you are **in opposition** of the RFC i.e. there **should** be a centralised memory logger on board

_votes are closed, when all the eligible voters have voted or it is midnight!_

**Comment by frroossst** [comment]
This RFC officially passes, with 6 votes in favour and 0 against.

For the time being we will not have a separate memory board on the rocket, this RFC **cannot be reopened**, if a discussion needs to be had on an adjacent topic, mention this RFC, but you have to open a new RFC. 

Thank you all for participating!
